numb = '89000000000'
numb1 = '+790012345'
numb2 = '+79781418474'
numb3 = '00000000000'
name1 = 'тест'
name2 = '原千五百秋瑞'
name3 = 'A' #a латинская
name4 = 'А' #кириллицей
num1 = '1'
elS = '!'
elS1 = '@'
nameAB = 'AB' #латинские
nameABK = 'АВ' #кириллицей
num2 ='12'
nameS = '!А'
nameASK = 'А -' #кириллицей
nameAS = 'A -' #латинские
namePP = '  ' #два пробела
namePY = ''
namePOP = 'Тестеровщик'
nameB30 = 'фывапролджэфывапролджэфывапролпрпоп'
name30 = 'фывапролджэфывапролджэфывапрол'
name2t = 'лорврромрм—лоррорм'
nameZn = '☺☻♥♦♣♠•◘'
nameAr = 'صسغذئآ'
nameC = '龍門大酒家家家家'
nameSS = '№;"?@%!*&%#'
nameJ = '№;"?@%!*&%'
nameAL = 'лджэфывап'
nameAK = '1233445'
fam_V = 'Скилфэктори'


num11 = '123456789'
num12 ='012346778912'
num13 ='0123456789013'
Lat11 ='Abcdefghijk'
KirE = 'Абвгдеёжзик@mail.ru'
SE = '☺☻♥♦♣♠•◘♠•◘@mail.ru'
ArE = ' صسغذئآصسغذئ@mail.com '
ChE = '龍門大酒家門大酒家酒家@mail.ru'
Ye =  '原千五百秋瑞千五百秋瑞@mail.ru'
SS =' №;"?@%№;"?@@bk.ru'
NE = 'невалид@мейл.ру'
T2T2 = 'test--2023.test@mail.com'
DlE505 = '14jYuZsGlJjYxOYdPTJebhuJgGgWuaYBpUbxEtxKEhGtXiuBkyCIufWQqTAbaXlAQzaZOEvvxRgGaMKTFLduRaouihOuXjxHqPXqbjzkjPSCYbtFaqiDBnzNcJymvCsPTAEWlFBofUqdhmSpOihjBumquPfqWXkmEUSvsXGQAVBwZZsSXsXQYnYPrCbCGoZRoJIBOgSRJpePQWGBlPCnrIlkOdYobRLcXFgbwxRmwySAvfHLiBVyhIudSNenbvyjzZxraJzMKupefOTeKoNiIiAfiEKIejvoABMdFYcUWsibgfmcsDnExHGpozUFTetzoCTSdTGckvgJicwngwV7EKIoBeGuYLCouOGOSZWMSPpPFCVSagjiXZIayxvZVWkdomVwMjxvOxpCotcTxAsVdQSTEujFqccMxVtWQayFdFDrDOrWMsRLymSNYgVyCLuIPMlcxhzFVFhMgpRwhHYfjQVWsLpaOpkhEnkflRtqkZQgFeOe@mail.com'
ML = 'helpsos1@bk.ru'

PrL_V = 'Test2023'
Pr7 = 'Lkjhgfd'
pr = 'lkjhgfds'
PrK = 'lлорпавн'
Pr21 = 'Lkjhgfdsapoiuytrewqas'
PrNV = 'Lkjhgfds1234'
Pr20 = 'Lkjhgfdsapoiuytrewqa'

numbN = '89787741773'